TEMPLATE =lib
QT += qml quick
QMAKE_CXXFLAGS += -fPIC
CONFIG += debug
CONFIG += dll
CONFIG += plugin
HEADERS += ConfiguratorUI.hpp
HEADERS += AppData.hpp
SOURCES += ConfiguratorUI.cpp
SOURCES += AppData.cpp
INCLUDEPATH += ../configurator
INCLUDEPATH += ../../system/jlib
INCLUDEPATH += ../../system/include
INCLUDEPATH += ../deploy
INCLUDEPATH += /opt/Qt/5.1.1/gcc_64/include
TARGET = ConfiguratorUI
